name: Build & Test
on:
  pull_request:
    branches:
      - master
jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16, 17, 18]
        script: ["dev", "dev:slow", "static:quick", "static"]
      fail-fast: false

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup node env 🏗
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          check-latest: true

      - name: Cache node_modules 📦
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies 👨🏻‍💻
        run: npm ci --prefer-offline --no-audit

      - name: Run tests 🧪
        run: npm run test

      - name: Build and serve 🔧
        env:
          FAIRTRACKS_GITHUB_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run ${{ matrix.script }}
